#ifndef PORT_METHANE_H
#define PORT_METHANE_H

#include <stdint.h>
#include "dev_methane.h"

#define PORT_METHANE_FRAME_MAX 48U
#define PORT_METHANE_COMMAND_DATA_LENGTH 2U
#define PORT_METHANE_COMMAND_FRAME_LENGTH 7U
#define PORT_METHANE_RESPONSE_MIN_LENGTH 14U
#define PORT_METHANE_RESPONSE_PREFIX_MIN_LENGTH 10U
#define PORT_METHANE_RESPONSE_TRAILER_LENGTH 5U
#define PORT_METHANE_RESPONSE_COMMA_COUNT 3U
#define PORT_METHANE_FIELD_VALUE_OFFSET 1U
#define PORT_METHANE_STATUS_HEX_DIGIT_COUNT 2U
#define PORT_METHANE_CONCENTRATION_DECIMAL_DIGITS 2U
#define PORT_METHANE_TEMPERATURE_DECIMAL_DIGITS 1U
#define PORT_METHANE_PRESSURE_DECIMAL_DIGITS 2U
#define PORT_METHANE_DECIMAL_RADIX 10U
#define PORT_METHANE_HEX_ALPHA_OFFSET 10U
#define PORT_METHANE_HEX_NIBBLE_BITS 4U
#define PORT_METHANE_HEX_NIBBLE_MASK 0x0FU
#define PORT_METHANE_FIELD_SECOND_VALUE_OFFSET 2U
#define PORT_METHANE_PARSE_MAX_ABS_VALUE 1000000L
#define PORT_METHANE_MAX_CONCENTRATION_CENTI_VOL 10000L
#define PORT_METHANE_MIN_TEMPERATURE_DECI_C (-400)
#define PORT_METHANE_MAX_TEMPERATURE_DECI_C 700
#define PORT_METHANE_MAX_PRESSURE_CENTI_MBAR 200000L

enum {
    PORT_METHANE_COMMAND_FIRST_BYTE_INDEX = 0U,
    PORT_METHANE_COMMAND_SECOND_BYTE_INDEX = 1U,
    PORT_METHANE_COMMAND_LRC_SEPARATOR_INDEX = 2U,
    PORT_METHANE_COMMAND_LRC_HIGH_INDEX = 3U,
    PORT_METHANE_COMMAND_LRC_LOW_INDEX = 4U,
    PORT_METHANE_COMMAND_CR_INDEX = 5U,
    PORT_METHANE_COMMAND_LF_INDEX = 6U,
    PORT_METHANE_RESPONSE_LRC_FIRST_DIGIT_OFFSET = 1U,
    PORT_METHANE_RESPONSE_LRC_SECOND_DIGIT_OFFSET = 2U,
    PORT_METHANE_RESPONSE_CR_OFFSET = 3U,
    PORT_METHANE_RESPONSE_LF_OFFSET = 4U
};

typedef struct {
    uint8_t data[PORT_METHANE_FRAME_MAX];
    uint8_t length;
    uint8_t overflow;
} MethaneFrameBuffer;

uint8_t PortMethane_Lrc(const uint8_t *data, uint8_t length);
uint8_t PortMethane_BuildCommand(MethaneSafeCommand command,
                                 uint8_t frame[PORT_METHANE_COMMAND_FRAME_LENGTH]);
DevStatus PortMethane_ParseR8(const uint8_t *frame, uint8_t length, MethaneSample *sample);
void PortMethane_BufferReset(MethaneFrameBuffer *buffer);
DevStatus PortMethane_BufferPush(MethaneFrameBuffer *buffer, uint8_t byte,
                                 MethaneSample *sample);

#endif
