#ifndef PORT_MODBUS_H
#define PORT_MODBUS_H

#define PORT_MODBUS_MIN_SLAVE_ADDRESS         1U
#define PORT_MODBUS_MAX_SLAVE_ADDRESS         247U
#define PORT_MODBUS_WRITE_SINGLE_REGISTER     0x06U
#define PORT_MODBUS_EXCEPTION_FUNCTION_MASK   0x80U
#define PORT_MODBUS_REQUEST_LENGTH            8U
#define PORT_MODBUS_RESPONSE_LENGTH           8U
#define PORT_MODBUS_EXCEPTION_LENGTH          5U
#define PORT_MODBUS_CRC_INITIAL_VALUE         0xFFFFU
#define PORT_MODBUS_CRC_POLYNOMIAL            0xA001U
#define PORT_MODBUS_CRC_DATA_LENGTH            6U
#define PORT_MODBUS_CRC_BITS_PER_BYTE         8U
#define PORT_MODBUS_RESPONSE_TIMEOUT_MS       100U

#endif /* PORT_MODBUS_H */
